### ISSUE TITLE
New Gosling features required for the SV project 

### ISSUE THREAD

**Issue by sehilyi** [sehilyi/gosving#2]
- [ ] Mouse events in circular tracks (https://github.com/gosling-lang/gosling.js/issues/274)
- [ ] Mouse hover effect to provide visual cues of interactions (https://github.com/gosling-lang/gosling.js/issues/31)
- [ ] Tooltips in circular tracks (https://github.com/gosling-lang/gosling.js/issues/30)
